In [1]:
# Question 1
import torch 
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0].item(), 2) == 0.09
output

/tmp/ipykernel_5703/3231285882.py:5: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  data = torch.Tensor([1, 2, 3])


tensor([0.0900, 0.2447, 0.6652])

In [2]:
# Question 2
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return torch.exp(x) / torch.sum(torch.exp(x), dim=0)

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1].item(), 2) == 0.26
output


tensor([0.7054, 0.0351, 0.2595])

In [4]:
# Question 3
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return torch.exp(x) / torch.sum(torch.exp(x), dim=0)

data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

In [6]:
# Question 4
import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdim=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(dim=0, keepdim=True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output



tensor([0.0900, 0.2447, 0.6652])

In [7]:
# Question 5
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int) -> None:
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: str) -> None:
        self._name = name
        self._yob = yob
        self._grade = grade
    
    def describe(self):
        return f"Student - Name: {self._name}, YOB: {self._yob}, Grade: {self._grade}"
    
student1 = Student(name="studentZ2023", yob=2011, grade="6")
assert student1._yob == 2011
student1.describe()


'Student - Name: studentZ2023, YOB: 2011, Grade: 6'

In [8]:
# Question 6
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int) -> None:
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str) -> None:
        self._name = name
        self._yob = yob
        self._subject = subject
    
    def describe(self):
        return f"Teacher - Name: {self._name}, YOB: {self._yob}, Subject: {self._subject}"
    
teacher1 = Teacher(name="teacherZ2023", yob=1991, subject="History")
assert teacher1._yob == 1991
teacher1.describe()

'Teacher - Name: teacherZ2023, YOB: 1991, Subject: History'

In [9]:
# Question 7 
from abc import ABC, abstractmethod

class Person(ABC):
    def __init__(self, name: str, yob: int) -> None:
        self._name = name
        self._yob = yob
    
    def get_yob(self):
        return self._yob
    
    @abstractmethod
    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str) -> None:
        self._name = name
        self._yob = yob
        self._specialist = specialist
    
    def describe(self):
        return f"Doctor - Name: {self._name}, YOB: {self._yob}, Specialist: {self._specialist}"

doctor1 = Doctor(name="doctorZ2023", yob=1981, specialist="Endorcrinologists")
assert doctor1._yob == 1981
doctor1.describe()

'Doctor - Name: doctorZ2023, YOB: 1981, Specialist: Endorcrinologists'

In [11]:
class Ward:
    def __init__(self, name: str) -> None:
        self.__name = name
        self.__list_of_people = []

    def add_person(self, person: Person):
        self.__list_of_people.append(person)

    def count_doctor(self):
        count = 0
        for person in self.__list_of_people:
            if isinstance(person, Doctor):
                count += 1
        return count

    def sort_age(self):
        return sorted(self.__list_of_people, key=lambda person: person.get_yob())

    def describe(self):
        print(f"Ward Name: {self.__name}")
        for person in self.__list_of_people:
            print(person.describe())


student1 = Student(name=" studentA ", yob=2010, grade="7")
teacher1 = Teacher(name=" teacherA ", yob=1969, subject=" Math ")
teacher2 = Teacher(name=" teacherB ", yob=1995, subject=" History ")
doctor1 = Doctor(name=" doctorA ", yob=1945, specialist=" Endocrinologists ")
# assert ward1.count_doctor() == 1
doctor2 = Doctor(name="doctorB", yob=1975, specialist=" Cardiologists ")
ward1 = Ward(name=" Ward1 ")
ward1 . add_person(student1)
ward1 . add_person(teacher1)
ward1 . add_person(teacher2)
ward1 . add_person(doctor1)
ward1 . add_person(doctor2)
ward1 . count_doctor()

2

In [12]:
class MyStack:
    def __init__(self, capacity: int):
        self.__capacity = capacity
        self.__stack = []
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value: int):
        if self.is_full():
            raise IndexError("Stack is full")
        self.__stack.append(value)

stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False

stack1.push(2)
print(stack1.is_full())

False


In [13]:
# Question 10
class MyStack:
    def __init__(self, capacity: int):
        self.__capacity = capacity
        self.__stack = []
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value: int):
        if self.is_full():
            raise IndexError("Stack is full")
        self.__stack.append(value)
    
    def top(self):
        if len(self.__stack) == 0:
            raise IndexError("Stack is empty")
        return self.__stack[-1]
    
stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1
print(stack1.top())

1


In [14]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def enqueue(self, value):
        ### Your Code Here
        if not self.is_full():
            self.__queue.append(value)
        else:
            raise OverflowError("Queue is full")
        ### End Code Here

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())


False


In [15]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def isEmpty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if not self.isEmpty():
            return self.__queue.pop(0)
        else:
            raise IndexError("Queue is empty")

    def enqueue(self, value):
        ### Your Code Here
        if not self.is_full():
            self.__queue.append(value)
        else:
            raise OverflowError("Queue is full")
        ### End Code Here

    def front(self):
        ### Your Code Here
        if not self.isEmpty():
            return self.__queue[0]
        else:
            raise IndexError("Queue is empty")
        ### End Code Here

queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())


1
