In [1]:
import numpy as np

In [2]:
# create a 1D array from 0 to 9
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1-a

In [4]:
# create a boolean array 3x3 with all values True
arr = np.ones((3, 3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2-b

In [5]:
arr = np.arange(0,10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


3c

In [6]:
arr = np.arange(0,10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

4b

In [13]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

5b

In [14]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

6a

In [15]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

7a

In [16]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


8a

In [17]:
a = np.array([2,6,1,9,10,3,27])
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

9c

In [18]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    # return x if x >= y else y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

10d

In [20]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
np.where(a < b, b, a)

array([6, 7, 9, 8, 9, 7, 5])

11a

In [3]:
!pip install gdown

  Using cached gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
  Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Using cached gdown-5.2.0-py3-none-any.whl (18 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.0/163.0 kB 2.0 MB/s eta 0:00:002.4 MB/s eta 0:00:01
Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cach

In [4]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /home/minhtranh/works/AIO2024-MAIN/Module-2/Exercise-M02W01/MCQs/dog.jpeg
100%|███████████████████████████████████████| 33.7k/33.7k [00:00<00:00, 820kB/s]
